sudo: false
language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

compiler:
- g++

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
